version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'advqr'
      MYSQL_USER: 'enescosanuz'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_PASSWORD: 'enescosanuz'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: